### ISSUE TITLE
V5.0 ESP32 ZigBee example fails to build

### ISSUE THREAD

**Issue by PerennialNovice** [Sloeber/arduino-eclipse-plugin#1706]
**Describe your environment**   

Sloeber 5.0.0.202501172146
OS: win11 
Zigbee_On_Off_Switch.ino from ESP32 board examples
nanoESP32-C6 v1.0

**Describe the bug**   

When building the example sketch, the build fails:

```
14:01:01 **** Incremental Build of configuration Release for project Test ****
Arduino Toolchain (Sloeber edition)
Info: Internal Builder is used for build
1
cmd /c if exist "C:\Users\user.name\Documents\sloeber5-workspace\Test\src\partitions.csv" COPY /y "C:\Users\user.name\Documents\sloeber5-workspace\Test\src\partitions.csv" "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\partitions.csv"
2
cmd /c if not exist "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\partitions.csv" if exist "C:\Sloeber5\arduinoPlugin\packages\esp32\hardware\esp32\3.1.1\variants\esp32c6\partitions.csv" COPY "C:\Sloeber5\arduinoPlugin\packages\esp32\hardware\esp32\3.1.1\variants\esp32c6\partitions.csv" "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\partitions.csv"
3
cmd /c if not exist "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\partitions.csv" COPY "C:\Sloeber5\arduinoPlugin\packages\esp32\hardware\esp32\3.1.1\tools\partitions\zigbee.csv" "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\partitions.csv"
        1 file(s) copied.
4
cmd /c IF EXIST "C:\Users\user.name\Documents\sloeber5-workspace\Test\src\bootloader.bin" ( COPY /y "C:\Users\user.name\Documents\sloeber5-workspace\Test\src\bootloader.bin" "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\Test.bootloader.bin" ) ELSE ( IF EXIST "C:\Sloeber5\arduinoPlugin\packages\esp32\hardware\esp32\3.1.1\variants\esp32c6\bootloader.bin" ( COPY "C:\Sloeber5\arduinoPlugin\packages\esp32\hardware\esp32\3.1.1\variants\esp32c6\bootloader.bin" "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\Test.bootloader.bin" ) ELSE ( "C:\Sloeber5\arduinoPlugin\packages\esp32\tools\esptool_py\4.9.dev3\esptool.exe" --chip esp32c6 elf2image --flash_mode dio --flash_freq 80m --flash_size 4MB -o "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\Test.bootloader.bin" "C:\Sloeber5\arduinoPlugin\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.3-cfea4f7c-v1\esp32c6\bin\bootloader_qio_80m.elf" ) )
esptool.py v4.8.1
Creating esp32c6 image...
Merged 2 ELF sections
Successfully created esp32c6 image.
5
cmd /c if exist "C:\Users\user.name\Documents\sloeber5-workspace\Test\src\build_opt.h" COPY /y "C:\Users\user.name\Documents\sloeber5-workspace\Test\src\build_opt.h" "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\build_opt.h"
6
cmd /c if not exist "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\build_opt.h" type nul > "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\build_opt.h"
7
cmd /c type nul > "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release/file_opts"
8
cmd /c COPY /y "C:\Sloeber5\arduinoPlugin\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.3-cfea4f7c-v1\esp32c6\sdkconfig" "C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release\sdkconfig"
        1 file(s) copied.
Starting C++ compile: sloeber.ino.cpp.o
"C:\Sloeber5\arduinoPlugin\packages\esp32\tools\esp-rv32\2405/bin/riscv32-esp-elf-g++"  -MMD -c "@C:\Sloeber5\arduinoPlugin\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.3-cfea4f7c-v1\esp32c6/flags/cpp_flags" -Wall -Wextra -Os -Werror=return-type -DF_CPU=160000000L -DARDUINO=20302 -DARDUINO_ESP32C6_DEV -DARDUINO_ARCH_ESP32 -DARDUINO_BOARD=\"ESP32C6_DEV\" "-DARDUINO_VARIANT=\"esp32c6\"" -DARDUINO_PARTITION_zigbee "-DARDUINO_HOST_OS=\"windows\"" "-DARDUINO_FQBN=\"esp32:esp32:esp32c6:CDCOnBoot=default,CPUFreq=160,DebugLevel=none,EraseFlash=none,FlashFreq=80,FlashMode=qio,FlashSize=4M,JTAGAdapter=default,PartitionScheme=zigbee,UploadSpeed=921600,ZigbeeMode=zczr\"" -DESP32=ESP32 -DCORE_DEBUG_LEVEL=0    -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=0 -DZIGBEE_MODE_ZCZR "@C:\Sloeber5\arduinoPlugin\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.3-cfea4f7c-v1\esp32c6/flags/defines" "-IC:\Users\user.name\Documents\sloeber5-workspace\Test\src" -iprefix "C:\Sloeber5\arduinoPlugin\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.3-cfea4f7c-v1\esp32c6/include/" "@C:\Sloeber5\arduinoPlugin\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.3-cfea4f7c-v1\esp32c6/flags/includes" "-IC:\Sloeber5\arduinoPlugin\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.3-cfea4f7c-v1\esp32c6/qio_qspi/include" "-IC:\Sloeber5\arduinoPlugin\packages\esp32\hardware\esp32\3.1.1\cores\esp32" "-IC:\Sloeber5\arduinoPlugin\packages\esp32\hardware\esp32\3.1.1\variants\esp32c6" "-IC:\Sloeber5\arduinoPlugin\packages\esp32\hardware\esp32\3.1.1\libraries\Zigbee\src" -MMD -MP "-MFsrc\sloeber.ino.cpp.d" "-MTsrc\sloeber.ino.cpp.o" -D__IN_ECLIPSE__=1 "@C:\Users\user.name\Documents\sloeber5-workspace\Test\bin\Release/file_opts" "..\..\src\sloeber.ino.cpp" -o "src\sloeber.ino.cpp.o"     
..\..\src\sloeber.ino.cpp:10:13: error: variable or field 'onZbButton' declared void
   10 | static void onZbButton(SwitchData *button_func_pair) ;
      |             ^~~~~~~~~~
..\..\src\sloeber.ino.cpp:10:24: error: 'SwitchData' was not declared in this scope
   10 | static void onZbButton(SwitchData *button_func_pair) ;
      |                        ^~~~~~~~~~
..\..\src\sloeber.ino.cpp:10:36: error: 'button_func_pair' was not declared in this scope
   10 | static void onZbButton(SwitchData *button_func_pair) ;
      |                                    ^~~~~~~~~~~~~~~~
In file included from ..\..\src\sloeber.ino.cpp:18:
C:\Users\user.name\Documents\sloeber5-workspace\Test\src\Zigbee_On_Off_Switch.ino:81:48: warning: ignoring attribute 'section (".iram1.1")' because it conflicts with previous 'section (".iram1.0")' [-Wattributes]
   81 | static void IRAM_ATTR onGpioInterrupt(void *arg) {
      |                                                ^
..\..\src\sloeber.ino.cpp:11:23: note: previous declaration here
   11 | static void IRAM_ATTR onGpioInterrupt(void *arg) ;
      |                       ^~~~~~~~~~~~~~~

14:01:14 Build Failed. 3 errors, 1 warnings. (took 12s.648ms)
```

**To Reproduce**   

1. fresh install of sloeber
2. fresh install of ESP32 3.1.1
3. new Arduino Sketch using Zigbee_On_Off_Switch example from Library->Board->Zigbee
4. verify

**Project properties:**

![Image](https://github.com/user-attachments/assets/e8b83d79-5a07-4da8-85c3-4e787499a8fa)

**Additional observations:**

Same example with the same properties works fine in Arduino IDE 2.3.4

Zigbee_On_Off_Light.ino example works in Sloeber v5.0

**Comment by jantje** [comment]
This is basically a duplicate of the known limitation #775
The solution is to move the stuff that causes the conflict to a header file and include that.
I header and ino that works

[Zigbee_On_Off_Switch.zip](https://github.com/user-attachments/files/18727432/Zigbee_On_Off_Switch.zip)

**Comment by PerennialNovice** [comment]
OK, hadn't seen that...
sorry for bothering you with long known stuff :/
